version: '3'

env:
  UNICRON_OUT: 'app/grpc/unicron'
  UNICRON_GRPC_OUT: 'app/grpc/unicron'

dotenv: ['.env']

tasks:
  unicron_proto:
    cmds:
      - python3 -m grpc_tools.protoc unicron.proto 
        --proto_path=. 
        --python_out=$UNICRON_OUT --grpc_python_out=$UNICRON_GRPC_OUT

  install_requirenments:
    cmds:
      - pip install poetry
      - poetry install
      
  check:
    cmds:
      - ruff check --fix .

  logs_db:
    cmds:
      - docker-compose logs -f optimus_prime_db

  logs_app:
    cmds:
      - docker-compose logs -f optimus_prime

  run:
    cmds:
      - docker-compose build
      - docker-compose up -d

  stop:
    cmds:
      - docker-compose down

  restart:
    cmds:
      - task: stop
      - task: run
    